### PR TITLE
Add Emoji Detection and Removal Functionality

### PR DESCRIPTION
**Pull request by PxPerfectMike**
Implemented functions to detect and remove emojis within the text. If the user enables the corresponding setting, these emojis will be automatically removed. This feature ensures that users have the option to exclude emojis from their texts, based on their preference set in the settings.

- Added function `isEmoji` to identify emojis in the text.
- Added function `ignoreEmojis` to remove the emojis from the text
- Integrated the above functions with the user settings to conditionally remove detected emojis.

Tested and working in both Chrome and Edge.

### CODE REVIEW

**Review by C-Nedelcu — APPROVED** [review]
That's fantastic, thanks a lot for implementing this change all the way through with an actual setting in the UI

**Comment by PxPerfectMike** [comment]
Yeah no problem at all! I think this is a great project and I would love to do some more work on it soon!

**Comment by C-Nedelcu** [comment]
> Yeah no problem at all! I think this is a great project and I would love to do some more work on it soon!

Amazing, it'd be so cool to have regular contributors. I am quite busy in real life and not updating this project as often as I should. If you have improvement ideas we should definitely consider them!

I have uploaded v2.7.2 to the Chrome and Edge stores and gave you credit for the bugfix.

Also note that I have moved the AI Speak Emoji setting a bit further down in the Advanced settings, I hope that's OK.

**Comment by PxPerfectMike** [comment]
It's completely okay that you moved the setting down, I just put it somewhere I thought was relevant but I think you know better than me. I would love to regularly contribute to this, I have a good amount of spare time myself currently and I just really love coding and helping. I will take a look at the issues list and see if I can tackle a few more problems and/or feature requests.

**Pull request merged**
